### ISSUE TITLE
Do not wait for element to have given style properties

### ISSUE THREAD

**Issue by mkusz** [pawel-marek/master#3]
This part of code will be hard to maintain in real application. What is someone will change some property by 1px or color? Test will fail, but application functionality will be working. Wrong approach.
https://github.com/pawel-marek/master/blob/20ab0e6813251a8081038b6a2df7df2622b4f1a7/Testowanie_p/POM_Sites/NewPet.cs#L40

**Comment by pawel-marek** [comment]
So, what is better solution in such case? I don't want to use Thread.Sleep method. IsElementClickable didn't work in my case. because button is clickable all the time.

**Comment by mkusz** [comment]
What state of the button are you waiting for? To be invisible (css style: "display: none")? If so, there is a specific wait for that.

**Comment by pawel-marek** [comment]
Yes, you have right, after some more digging I found a different way for that, the following wait method will be probably better:

`ExpectedConditions.PresenceOfAllElementsLocatedBy(By.XPath("//*[@id='ui-datepicker-div'][contains(@style, 'display: none')]")));`

**Comment by mkusz** [comment]
Seems to be better, but your locator is still based on CSS style. Maybe you could try something like this:
`ExpectedConditions.invisibilityOfElementLocated(By.XPath("//*[@id='ui-datepicker-div']"));`

**Comment by pawel-marek** [comment]
No, it doesn't work in my case (I was trying it also before), therefore I've decided to add: [contains(@style, 'display: none')], the problem is that after clicking on 'ui-datepicker-div' the calendar is displayed, where user can set a date,I need to wait when calendar is closed (style = display: none).

**Comment by pawel-marek** [comment]
Yes, you right. With `invisibilityOfElementLocated ` I need only one locator. Thank you for your tip.
