### ISSUE TITLE
Mock or tests data?

### ISSUE THREAD

**Issue by mkusz** [pawel-marek/master#5]
Those list are some mocks or data used by test? If it's date store it in external file. If it's mock, add some comment.

https://github.com/pawel-marek/master/blob/3cf6a5c247fe796aa1e80c34ab8654a30b5c407a/Testowanie_p/Helpers/PetClinicStructure.cs#L13

**Comment by pawel-marek** [comment]
Those list I'm using as expected results for assertions.

**Comment by mkusz** [comment]
Even if it's expected result it's still some test data and should be moved to some external file that is no C# code (like: json, yaml, xml, ini, etc.) and list should be created dynamically from that external file.

**Comment by pawel-marek** [comment]
I've changed test structure, now I'm using xml file. Could you have a look on it and let me know of your opinion, please?

**Comment by mkusz** [comment]
Seems ok.
Just one comment: it's rather "TestsParameters" or "TesstData" not "TestConfiguration".
